version: '3'
  
services:
  app:
    image: deividroger/hello-express:latest
    ports:
    - 3000:3000
    deploy:
      mode: replicated
      replicas: 3
      restart_policy:
        condition: on-failure
