---

- hosts: all
  remote_user: deivid
  become: yes
  
  tasks:
    - name: Install nginx
      apt:
        name: nginx
        state: present
        update_cache: yes

    - name: Init nginx
      service:
        name: nginx
        state: started
        